### ISSUE TITLE
Include localhost server in every spec file

### ISSUE THREAD

**Issue by raffrearaUS** [isa-group/oas-generator#15]
Include localhost server in every spec file for easier testing with swagger-ui.

**Comment by raffrearaUS** [comment]
NOTE: not all files have been tested. #18 might help.

**Comment by pjmolina** [comment]
As commented before: Adding `localhost:8080` to contracts presumes the machine and port.
Instead of that:

1. server can be used specified.
2. dynamically, in run-time, if no server is defined, `localhost:<port>` can be provided based in the PORT in use

**Comment by raffrearaUS** [comment]
After commit d6c5e5ff6f9457cad1e6ad64e6f900d54465ea93, servers generated with oas-generator will add a localhost server to the contract if it was not already defined. The port will be the one specified in the variable named "serverPort".
